#!/usr/bin/python3.6

'''

bcp.py: basemount cp

    Step 2 of the BaCR pipeline. Copies and organizes .fastq files from an
    Illumina amplicon NGS run using the layout of basemount (a tool to
    mount one's Basespace account as a linux filesystem). .fastq files are
    organized by forward/reverse read, projectID and guide sequence. bcp
    was designed to put data from multiple projects with one or more guide
    sequences each into a format that can be easily batch analyzed

    Designed for use by UIC's Genome Editing Core
    
    Written by Cody Hasty in vim 7.4 on centos 7 on 08/2019

Usage:

    bcp.py -flag path_to_basemount_folder bacr_spreadsheet.csv

    flags:
        -p  Download from Basespace "Projects" folder
        -r  Download from Basespace "Runs" folder
        -d  Download from folder generated by Basespace downloader
        -s  bcp.py is skipped (used by BaCR.sh)
        -h  help: list an example of bcp.py usage

    ##NOTE: The files are copied and organized into the current working
    directory. Remember to cd into the place you wish to place your files

'''

import pandas
from pathlib import Path
import re
import shutil
import sys

###########################################################################

#
## validates argc, flag, and filepaths. exit bcp if -s flag is present
#

def checkInputs():
    # skip flag: exit program
    if str(sys.argv[1]) == '-s':
        print('Skip flag detected, exiting bcp.py')
        exit()
    # help flag
    if str(sys.argv[1]) == '-h':
        print('''
        bcp.py: basemount cp 

            Step 2 of the BaCR pipeline. Copies and organizes .fastq files from an
            Illumina amplicon NGS run using the layout of basemount (a tool to
            mount one's Basespace account as a linux filesystem). .fastq files are
            organized by forward/reverse read, projectID and guide sequence. bcp
            was designed to put data from multiple projects with one or more guide
            sequences each into a format that can be easily batch analyzed

            Designed for use by UIC's Genome Editing Core

            Written by Cody Hasty in vim 7.4 on centos 7 on 08/2019

        Usage:

            bcp.py -flag abs_path_to_basemount_folder bacr_spreadsheet.csv

        flags:
            -p  Download from Basespace "Projects" folder
            -r  Download from Basespace "Runs" folder
            -d  Download from folder generated by Basespace downloader
            -s  bcp.py is skipped (used by BaCR.sh)
            -h  help: list an example of bcp.py usage

            ##NOTE: The files are copied and organized into the current working
            directory. Remember to cd into the place you wish to place your files
        ''')
        exit()
    # check argc
    if len(sys.argv) != 4:
        print("Error: Invalid command line arguments")
        print("Example: bcp.py -p path_to_basemount_folder bacr_csv")
        exit()
    # check flag
    if str(sys.argv[1]) not in ['-p', '-r', '-d', '-s']:
        print("Error: Invalid flag")
        print('''flags: 
            -p\tDownload from Basespace "Projects" folder
            -r\tDownload from Basespace "Runs" folder
            -d\tDownload from folder generated by Basespace downloader
            -s\tbcp.py is skipped (used by BaCR.sh)
            -h\thelp: list an example of bcp.py usage''')
        exit()
    # check basemount filepath. It will almost always be an absolute path
    if Path(str(sys.argv[2])).exists() == False:
        print('Error: Invalid path to basemount directory')
        print('Make sure you are using the correct absolute path')
        exit()
    # check csv filepath
    if Path(str(sys.argv[3])).exists() == False:
        print('Error: Invalid path to BaCR csv file')
        exit()

    return

###########################################################################

#
## creates a directory for each project and the appropriate 
## subdirectory for each guide in their respective projects
#

def buildRunDirectory(csvFile):
    for i in range(len(csvFile.Projects)):
        try:
            #make project dir
            Path(str(csvFile.Projects[i])).mkdir()
            if str(csvFile.GuideNames[i]) == 'nan':
                #empty GuideName, make proj subdir
                buildProjectSubdirectory(str(csvFile.Projects[i]))
            else:
                #add guide subdir to new proj dir
                buildGuideSubdirectory(str(csvFile.Projects[i]), 
                                       str(csvFile.GuideNames[i]))
        except FileExistsError:
            #project dir exists, add guide subdir to it
            buildGuideSubdirectory(str(csvFile.Projects[i]),
                                   str(csvFile.GuideNames[i]))

    return

###########################################################################

#
## creates the subdirectory structure for a given guide
#
        
def buildGuideSubdirectory(projectID,guideName):
  Path(f'{projectID}/{guideName}').mkdir()
  Path(f'{projectID}/{guideName}/R1').mkdir()
  Path(f'{projectID}/{guideName}/R2').mkdir()

  return

###########################################################################

#
## creates the subdirectory structure for a project with one guide
#

def buildProjectSubdirectory(projectID):
  Path(f'{projectID}/R1').mkdir()
  Path(f'{projectID}/R2').mkdir()

  return

###########################################################################

#
## removes jargon common to all .fastq file names using re and returns a
## string with the cleaned up name
#

def cleanupName(fastqName):
    fastqRegEx = re.compile(r'''(
        (\S+)           ## sample name, group 2
        _S\d+_L001      ## jargon common to all fastq file names
        (_R(1|2))       ## Forward/Reverse read, groups 3 and 4
        _001            ## more jargon
        (.fastq.gz)     ## file suffix, group 5
    )''', re.VERBOSE)

    matchObject = fastqRegEx.search(fastqName)
    
    return f'{matchObject.group(2)}{matchObject.group(3)}{matchObject.group(5)}'

###########################################################################

#
## helper function for cpFastq. copies .fastq with clean name to
## destinationPath. prints result of copy to stdout
#

def cpPrint(fastqPath, destinationPath, sampleName):
    destPathNewName = destinationPath / sampleName
    if shutil.copy(fastqPath, destPathNewName):
        print(f'copying {fastqPath.name} to {destPathNewName}')
    
    return

###########################################################################

#
## matches .fastq to its respective directory, then calls cpPrint
#

def cpFastq(fastq, csvFile):
    sampleName = cleanupName(fastq.name)
    for i in range(len(csvFile.Projects)):
        if str(csvFile.Projects[i]) in sampleName:
            # fastq matched to dir
            if str(csvFile.GuideNames[i]) == 'nan':
                # no GuideName, cp to projSubDir
                if '_R1' in sampleName:
                    cpPrint(fastq, Path(f'{csvFile.Projects[i]}/R1'),
                            sampleName)
                else:
                    cpPrint(fastq, Path(f'{csvFile.Projects[i]}/R2'),
                            sampleName)
            elif str(csvFile.GuideNames[i]) in sampleName:
                # fastq matched to GuideName, cp to guideSubDir
                if '_R1' in sampleName:
                    cpPrint(fastq,
                    Path(f'{csvFile.Projects[i]}/{csvFile.GuideNames[i]}/R1'),
                    sampleName)
                else:
                    cpPrint(fastq,
                    Path(f'{csvFile.Projects[i]}/{csvFile.GuideNames[i]}/R2'),
                    sampleName)
    return
  
###########################################################################

#
## Loops through .fastq files according to the directory structure of
## basemountDir/Projects/, and calls cpFastq on each
#

def cpFromProjects(csvFile, basemountPath):
    #loop through sample directories
    for sampleDir in basemountPath.glob('./Samples/*'):
        #exclude hidden files
        if sampleDir.name.startswith('.'):
            continue
        #loop through fastq files in each sample directory
        for fastq in sampleDir.glob('./Files/*'):
            cpFastq(fastq, csvFile)

    return

###########################################################################

#
## Loops through .fastq files according to the directory structure of
## basemountDir/Runs, and calls cpFastq on each
#

def cpFromRuns(csvFile, basemountPath):
    #loop through index directories
    for indexDir in basemountPath.glob('./Properties/Output.Samples/*'):
        #exclude hidden files
        if str(indexDir.name).startswith('.'):
            continue
        #loop through fastq files in each index directory
        for fastq in indexDir.glob('./Files/*'):
            cpFastq(fastq, csvFile)

    return

###########################################################################

#
##
#

#def cpFromDownloader():

               
####MAIN###################################################################

checkInputs()
 
# declare variables
bcpFlag = str(sys.argv[1])
basemountPath = Path(str(sys.argv[2]))
csvFile = pandas.read_csv(sys.argv[3])

buildRunDirectory(csvFile)

if bcpFlag == '-r':
    cpFromRuns(csvFile, basemountPath)
elif bcpFlag == '-p':
    cpFromProjects(csvFile, basemountPath)
#elif bcpFlag == 'd':
#    cpFromDownloader()
